---
- name: Enable update service
  ansible.windows.win_service:
    name: Windows Update
    state: started
    start_mode: auto

- name: Gather local admins group name multilingual
  ansible.windows.win_shell: |
    (Gwmi win32_group -Filter "SID='S-1-5-32-544'").Name
  register: localadmin_group_name

- name: Add SCOMAdmins Group as Local Administrator
  ansible.windows.win_group_membership:
    name: "{{ (localadmin_group_name.stdout|split('\n'))[0]|trim }}" # Administrators
    members:
      - '{{ ludus_domain_netbios_name }}\{{ scom_admin_group }}'
    state: present

- name: Begin OMReporting Install
  ansible.builtin.include_tasks:
    file: install.yml
